### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by ForbesLindesay**
This is a crude attempt at fixing the memory leak caused by code like:

```js
function next() {
  return new Promise(function (resolve) {
   setImmediate(resolve)
  }).then(next)
}
next()
```

In theory this should be a viable way of running a continuous polling operation.

### CODE REVIEW

**Comment by nathan7** [comment]
@ForbesLindesay I've been contemplating doing this for a long time, and I probably have a local branch around doing a similar thing. Collapsing promise chains like this should be a nice perf boost.
My own plan was to stick a few private symbols on the `then` function, containing the state. Handlers could be offloaded onto that promise straight away, and synchronous inspection becomes feasible too. I can't find my version of the code right now, but I have a feeling it'll be faster than invoking further dynamic dispatch.

**Comment by nathan7** [comment]
I think depending on [es6-symbol](https://www.npmjs.com/package/es6-symbol) and sticking everything under `then` should resolve privacy/encapsulation concerns. I'll have to run some perf tests on the cost of messing with function properties. I'm not sure how those'll turn out, but I'd rather not lose the semantic niceties of that to the Perf Monster.

**Comment by ForbesLindesay** [comment]
The encapsulation is just as good if we use es6-symbol on `this` rather than `this.then` so I would suggest sticking with that as it seems simpler.

**Comment by nathan7** [comment]
Sure, but `.then` can freely be moved around and replaced. We could get some very weird behaviour on subclasses.

**Comment by nathan7** [comment]
https://github.com/promises-aplus/promises-spec/issues/179

**Comment by ForbesLindesay** [comment]
I now believe this is ready to merge, and it fixes a major memory leak.  @nathan7 if you can review this asap and do the honours, that would be great.

**Comment by ForbesLindesay** [comment]
I'm merging this now to get unblocked, but I'd still love a review if someone gets a chance.

**Comment by nathan7** [comment]
Looks good to me, @ForbesLindesay! Clever trick with the `internalHandle` fn!

**Pull request merged**
